apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-distributed
spec:
  selector:
    matchLabels:
      app: nginx-distributed
  replicas: 9
  template:
    metadata:
      labels:
        app: nginx-distributed
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        # loki: "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nginx-distributed
              topologyKey: topology.kubernetes.io/zone
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
